/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tests;

public class App {
    public int getGreeting() {
	int x = 0;
	int i = 0;
	while(i<1000000){

		if((i%10000)==0){
			System.out.println("Hello");
			x++;
		}
		i++;
	}
        return x;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
