/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tests;

public class App {
    public int getGreeting() {
        return 22*32;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
